import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNavbar from "@/components/navbar/MainNavbar";


export const metadata = {
  title: "Vortex",
  description: "Generated by Hamza",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          className="h-[100svh] w-full flex flex-col items-center"
          style={{
            background: "linear-gradient(to right, #402fff, #7902df)"
          }}
        >
          <div className="h-[10svh] w-11/12 flex flex-col items-center justify-center">
            <MainNavbar />
          </div>
          <div className="h-[90svh] w-full px-12 pt-6" style={{borderTop: "2px solid #ffffff20"}}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
